# Generated by Django 3.1 on 2020-09-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200907_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='memory_variant',
            new_name='memory',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='ram',
            new_name='ram_variant',
        ),
    ]
