# Generated by Django 3.1 on 2020-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color_variant', models.CharField(max_length=100)),
                ('memory_variant', models.IntegerField()),
                ('sim_type', models.CharField(max_length=50)),
                ('battery', models.IntegerField()),
                ('processor', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('front_camera', models.IntegerField()),
                ('rear_camera', models.IntegerField()),
                ('resolution', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
