# Generated by Django 3.1 on 2020-09-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200907_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='name',
            field=models.TextField(default='laptop', max_length=50),
            preserve_default=False,
        ),
    ]
